var GAME_LEVELS = [

  ["  x                                                                       x  ",
   "  x                                                                       x  ",
   "  x                                                                       x  ",
   "  x                                                                       x  ",
   "  x                                                                       x  ",
   "  x                                                                       x  ",
   "  x                                                                       x  ",
   "  x                         r                                             x  ",
   "  x                                                                       x  ",
   "  x                o            xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   xxxxx  ",
   "  x                                                                       x  ",
   "  x              o o o                                                    x  ",
   "  x            xxxxxxxxx                                   xxxxxxxxxxxxxxxx  ",
   "  x                                                 xxxxxxxx              x  ",
   "  x                                  o o      xxxxxxx                     x  ",
   "  x                                                                       x  ",
   "  x                                 xxxxx                                 x  ",
   "  x                                                                       x  ",
   "  x               o                   o                                   x  ",
   "  x                                                                       x  ",
   "  x            xxxxx            G  xxxxxxx         o                x!!!!!x  ",
   "  x          xxxxxxx                                            o   x!!!!!x  ",
   "  x   @    xxxxxxxxx                                                xxxxxxx  ",
   "  xxxxxxxxxxxxxxxxxxxxxx      xxxxxxxxxxxxxxxxx         xxxxxxx   xxxxxxxxx  ",
   "                       x      x               xxx     xxx     x!!!x          ",
   "                       x!!!!!!x                 x!!!!!x       xxxxx          ",
   "                       x!!!!!!x                 x!!!!!x                      ",
   "                       xxxxxxxx                 xxxxxxx                      ",
   "                                                                             ",
   "                                                                             "],
   
   
   
   
   
  ["                         xxxxxxxxxxxxxxxxxxxxxxxxxxxxx              xx!xx            xx!xx                                         ",
   "                         x                                            v                v                                           ",
   "                         x                                                                                                         ",
   "                         x      xxxxxxxxxxxxxxxxxxxxxxxxx                                                                          ",
   "                         x   o xxxxxxxxxxxxxx                                               xxxxxxxxxxxxxx                         ",
   "                         x      xxxxxxxxxx                                     o     xxxxx                  o                      ",
   "                         x                                                                                                         ",
   "                         x                                     o     xxxx    xxxxx                          o                      ",
   "                         xxxxxxxxxxxxx                                                                                             ",
   "                                     xxx                     xxxxx                                          o                o     ",
   "                                       xxxxx                                                                                       ",
   "                                                xxxxx                                                     xxxxxx        xxxxxxxxxxx",
   "                                                x!!!x                                                                              ",
   "                                               xx!!!xx                      xx                                                     ",
   "                  r                            x  v  x             r       xxxxx                                                   ",
   "                                               x     x                      xx xxx                                                 ",
   "                                               x     xxxxxxx                 xxxxxxxxx                                             ",
   "                                               x                               xxxxxxxx                            x               ",
   "                                               x                            o   xxxx!!xxx                            x             ",
   "               x     x                         x     xxxxxxxxxxxx     xxx       xxxx!!!xx                            xx            ",
   "     @       xxx     xxx                       x     x                 xxxx       xxxxxxx                             xx           ",
   "    xxx      x         x                       x     x                  xxxxxx     xxxx                                xx          ",
   "    x x      x         x                       x     x                    xxxxxx  xxxxx                                 xxx        ",
   "!!!!x x!!!!!!x         x!!!!!!xxxxxxxxx!!!!!!!!xx    x!!!!!!x              xxxxxxxxxx                                   xxxx       ",
   "!!!!x x!!!!!!x         xxxxxxxx       xxxxxxxxxx     x!!!!!!xx             xxxxxxxxx         !!!!!!!!                   xxxx       ",
   "!!!!x x!!!!!!x                                       x!!!!!!xx            xxxxxxxxx!!!     !!xxxxxxxx!!!!               xxxxx      ",
   "!!!!x x!!!!!!x                    o                  x!!!!!!xx          xxxxxxxxxxxxxx!!!!!xxxxxxxxxxxxxx!!!!!!!!!!xxxxxxxxx       ",
   "!!!!x x!!!!!!x         xxxxxxxx       xxxxxxxxxxxxxxxx!!!!!!xx         xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx          ",
   "!!!!x x!!!!!!x         x!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx            ",
   "!!!!x x!!!!!!xxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!"],
   
   
   
   
   
   
   
  ["  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "  x                                                                                         x",
   "  x     ||                                                                                  x",
   "  x                                                                                         x",
   "  x                                                                                         x",
   "  x                                                           ||           xxxxx            x",
   "  x                                       ||                               xxxxx            x",
   "  x                                                                        xxxxx            x",
   "  x                                                                       xxxxxxx           x",
   "  x                                                                        x!x!x            x",
   "  x                                                o                  x    xxxxx    x       x",
   "  x                  ||     o                                        xxxx x xxx x xxxx      x",
   "  x                                                                 x x xxxx   xxxx x x     x",
   "  x                xxxxxx       xxxxxxxxxxx       xxx                    xxxxxxxxx          x",
   "  x              xx                                                       xxxxxxx           x",
   "  xxx                                                                     xxxxxxx           x",
   "  x    xxxx                                                               xxxxxxx           x",
   "  x        x                                           ||                  xxxxx            x",
   "  x o         ||                                                      o    xxxxx            x",
   "  x                                                                        xxxxx            x",
   "  x                                                                         x x             x",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  o  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "  x                                  x                                                      x",
   "  x      =                          xx                                                      x",
   "  x                                                                                         x",
   "  x                                                         x  x  x                         x",
   "  x                    xxxxxxxxxxxxxxx                      x  x  x                         x",
   "  x          o                                  =           xxxxxxx                         x",
   "  x                                                           xxx                           x",
   "  x       xxxxxxxx                                     o       x                            x",
   "  x                    xxxx                         xxxxxxx    x     xxxxxx                 x",
   "  x   =                            o        xxx                x    xxxxxxxx                x",
   "  x                                                            x    x!!!!xxx                x",
   "  x                             xxxxxxxx                       x    xxxxxxxx                x",
   "  x                                                            x    xxxxxx xxx              x",
   "  x                        xxxx                                x  xxxxxx xxxxx              x",
   "  x               o                      =                    xxxxx xxxx xx!xx              x",
   "  x                                                            xx   xxxx x!!!x              x",
   "  x          xxxxxxxxxxx                                       x   xxxxx xx!xx              x",
   "  x                                                            x  xxxxxxx xxx               x",
   "  xxxxx                                                        x     x   x x                x",
   "  x                                                                  x   x                  x",
   "  x                                                                  x   x                  x",
   "  x      @                                           o      =        x   x                  x",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                             ",
   "                                                                                             "],
   
   
   
   
   
   
   
  ["                                                                                             ",
   "                                                                                             ",
   "                                                                                             ",
   "                                                                                             ",
   "                                                                                             ",
   "             x      x   xx    x    x         x       x  xxxxxxx  x    x      x               ",
   "              x    x   x  x   x    x         x       x     x     xx   x      x               ",
   "               x  x   x    x  x    x         x       x     x     x x  x      x               ",
   "                xx    x    x  x    x         x   x   x     x     x  x x      x               ",
   "                xx     x  x    x  x           x x x x      x     x   xx                      ",
   "                xx      xx      xx             x   x    xxxxxxx  x    x      x               ",
   "                                                                                             ",
   "                                                                                             ",
   "                                                                                             ",
   "                                                                                             ",
   "                                                                                             ",
   "                                                                                             ",
   "   @                                                                                         ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                             "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
